### ISSUE TITLE
USER STORY: As a Site User I would like to create an account so that I can create and save recipes

### ISSUE THREAD

**Issue by LanaCreegan** [LanaCreegan/pp4#1]
EPIC: Create Account

As a **Site User** I would like to **create an account** so that I can **create and save recipes**

**Acceptance Criteria**

- [ ] User can see the signup button on the homepage and when clicked it will navigate them to a registration page
- [ ] Empty fields will be provided for the user to enter their name, email address and password
- [ ] A sign up button will be provided at the bottom of this registration page for users to sign up once these fields have been entered

**Tasks**

- [ ] Task 1: Implement call to action on the homepage for the user to register an account
- [ ] Task 2: Clear and easy to use registration process
- [ ] Task 3: User won't be allowed to register unless they have filled in all required fields
