### ISSUE TITLE
USER STORY: User Profile

### ISSUE THREAD

**Issue by LanaCreegan** [LanaCreegan/pp4#20]
EPIC: #14 

As a **Site User** I can **edit my profile** so that **I can update my details**

**Acceptance Criteria**

- The user is able to edit their profile to add details to it
- Only a user who is logged into their own page can edit it

**Tasks**

- [ ] Task 1: Implement an edit button so users can edit their profile
- [ ] Task 2: Implement a page in the users profile where they can edit their details
- [ ] Task 3:  Any user that isn't logged in or not registered won't be able to see the edit button on a profile
