### ISSUE TITLE
USER STORY: Recipe View

### ISSUE THREAD

**Issue by LanaCreegan** [LanaCreegan/pp4#3]
EPIC: Recipe View

As a **Site User** I can **view the recipes on the site** so that **try them at home**

**Acceptance Criteria**

- [ ]  When the user navigates to the recipe page they can see the full list of recipes available
- [ ]  When the user clicks on the recipe they are shown the full recipe instructions and ingredients

**Tasks**

- [ ] Task 1: Implement a recipe page to the navigation bar
- [ ] Task 2: The recipe page should contain all recipes on the site
- [ ] Task 3: A recipe shoould be a card that contains a brief summary of the recipe
- [ ] Task 4: Implement a detailed recipe page where instructions and ingredients are outlined for the user
