### ISSUE TITLE
USER STORY: Delete a Recipe

### ISSUE THREAD

**Issue by LanaCreegan** [LanaCreegan/pp4#5]
EPIC: Delete a Recipe

As a **Site User** I can **delete a recipe I have created** so that **it can be removed from the site**

**Acceptance Criteria**

- [ ] - The user is given the option to delete a recipe they have created
- [ ] - The user is given a confirmation window asking them if they want to delete the recipe
- [ ] - Once they confirm they want to delete the recipe it is then deleted
- [ ] - The user is given a confirmation that the recipe has been deleted
- [ ] - A user who is not logged in and who has not created the recipe won't be able to delete a recipe

**Tasks**

- [ ] Task 1: Implement button to allow the user to delete a recipe
- [ ] Task 2: Implement a confirmation window to insure that the user does want to delete a recipe
- [ ] Task 3: Prevent users who are not signed in or who are not registered from deleting a recipe by directing to an error page
- [ ] Task 4: Implement a message to the user that the recipe has been deleted
