### ISSUE TITLE
USER STORY: Search For Recipes

### ISSUE THREAD

**Issue by LanaCreegan** [LanaCreegan/pp4#9]
EPIC:  Search For Recipes

As a **Site User** I can **search for recipes on the site** so that **I can try a new recipe I've never cooked before**

**Acceptance Criteria**

- [ ] - The user is shown a recipe button in the navigation bar that brings them to the recipe page
- [ ] - The user can see other recipes and their own ones that they have posted on the site
- [ ] - The user does not need to be logged in/registered to view the recipes

**Tasks**

- [ ] Task 1: Implement a recipe section in the navigation bar to bring the user to the recipe page
